pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/var/jenkins_home/maven/bin/mvn -B -DskipTests clean package'
            }
        }
        //stage('Test') {
        //    steps {
        //       sh 'mvn test'
        //    }
        //    post {
        //        always {
        //            junit 'target/surefire-reports/*.xml'
        //        }
        //     }
        //}
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
